"use strict";

const stores = [
  {
    name: "호접몽",
    address: "경기도 용인시 처인구 남동 산 26-3",
    type: "chinese",
    subName: "중식",
    imagePath: "uploads/chinese1.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "하오차이나",
    address: "경기도 용인시 처인구 남동 50-3",
    type: "chinese",
    subName: "중식",
    imagePath: "uploads/chinese2.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "화미가",
    address: "경기도 용인시 처인구 역북동 721-1번지 상가동 103호",
    type: "chinese",
    subName: "중식",
    imagePath: "uploads/chinese3.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "진짜루중화요리",
    address: "경기도 용인시 처인구 남동 615-2",
    type: "chinese",
    subName: "중식",
    imagePath: "uploads/chinese4.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "홍콩반점",
    address: "경기도 용인시 처인구 김량장동 4-2",
    type: "chinese",
    subName: "중식",
    imagePath: "uploads/chinese5.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "백리향",
    address: "경기도 용인시 처인구 마평동 717-4",
    type: "chinese",
    subName: "중식",
    imagePath: "uploads/chinese6.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "향리반점",
    address: "경기도 용인시 처인구 김량장동 133-100",
    type: "chinese",
    subName: "중식",
    imagePath: "uploads/chinese7.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "향화루",
    address: "경기도 용인시 처인구 김량장동",
    type: "chinese",
    subName: "중식",
    imagePath: "uploads/chinese8.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "스시환",
    address: "경기도 용인시 처인구 역북동 중부대로 1331번길 6-3",
    type: "japanese",
    subName: "일식",
    imagePath: "uploads/japanese1.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "제철그륵",
    address: "경기도 용인시 처인구 명지로 269",
    type: "japanese",
    subName: "일식",
    imagePath: "uploads/japanese2.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "해랑",
    address: "경기도 용인시 처인구 동부로 35",
    type: "japanese",
    subName: "일식",
    imagePath: "uploads/japanese3.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "키와마루아지",
    address: "경기도 용인시 처인구 역북동 756",
    type: "japanese",
    subName: "일식",
    imagePath: "uploads/japanese4.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "시오",
    address: "경기도 용인시 처인구 김량장동 금령로 61 2층",
    type: "japanese",
    subName: "일식",
    imagePath: "uploads/japanese5.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "모로미",
    address: "경기도 용인시 처인구 명지로 60번길 8-3 1층 106호",
    type: "japanese",
    subName: "일식",
    imagePath: "uploads/japanese6.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "담어일식",
    address: "경기도 용인시 처인구 역북동 550-7번지 1층",
    type: "japanese",
    subName: "일식",
    imagePath: "uploads/japanese7.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "스시도도",
    address: "경기도 용인시 처인구 명지로 60번길 8-10 1층 101호",
    type: "japanese",
    subName: "일식",
    imagePath: "uploads/japanese8.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "카츠랩",
    address: "경기도 용인시 처인구 금령로 93번길 7-1",
    type: "japanese",
    subName: "일식",
    imagePath: "uploads/japanese9.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "오와스시 처인구점",
    address: "경기도 용인시 처인구 김량장동 금령로 85번길 3",
    type: "japanese",
    subName: "일식",
    imagePath: "uploads/japanese10.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "자작나무이야기",
    address: "경기도 용인시 처인구 양지면 대대리 20",
    type: "western",
    subName: "퓨전 음시점",
    imagePath: "uploads/western1.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "역북양식",
    address: "경기도 용인시 처인구 명지 구갈로 60번길 19-1",
    type: "western",
    subName: "이탈리아 요리",
    imagePath: "uploads/western2.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "리에또부리또",
    address: "경기도 용인시 처인구 남동 615-1번지 105호",
    type: "western",
    subName: "부리토",
    imagePath: "uploads/western3.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "토마토아저씨 용인점",
    address: "경기도 용인시 처인구 김량장동 293-20",
    type: "western",
    subName: "미국 서부 요리",
    imagePath: "uploads/western4.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "고급양식",
    address: "경기도 용인시 수지구 죽전 2동 589-19",
    type: "western",
    subName: "음식점",
    imagePath: "uploads/western5.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "뜰안애",
    address: "경기도 용인시 처인구 이동면 천리 515-2",
    type: "korean",
    subName: "한식",
    imagePath: "uploads/korean1.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "따뜻한밥상",
    address: "경기도 용인시 처인구 역북동 482-7",
    type: "korean",
    subName: "한식",
    imagePath: "uploads/korean2.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "밀보리식당",
    address: "경기도 용인시 역북동 482-7",
    type: "korean",
    subName: "한식",
    imagePath: "uploads/korean3.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "송담숯불구이",
    address: "경기도 용인시 김량장동 316-3 101호",
    type: "korean",
    subName: "한국식 BBQ",
    imagePath: "uploads/korean4.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "도도한밥상",
    address: "경기도 용인시 처인구 삼가동 320-9번지 1층",
    type: "korean",
    subName: "한식",
    imagePath: "uploads/korean5.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "돼지삼촌네",
    address: "경기도 용인시 처인구 포곡읍 마성리 284-1번지 201호",
    type: "korean",
    subName: "한식",
    imagePath: "uploads/korean6.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "푸른감람나무 한식부페",
    address: "경기도 용인시 포곡읍 둔전리 201-1",
    type: "korean",
    subName: "한식",
    imagePath: "uploads/korean7.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "큰손",
    address: "경기도 용인시 김량장동 254-50",
    type: "korean",
    subName: "한식",
    imagePath: "uploads/korean8.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "들꽃한정식",
    address: "경기도 용인시 처인구 이동면 백자로156번길 23",
    type: "korean",
    subName: "한식",
    imagePath: "uploads/korean9.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "또오래분식",
    address: "경기도 용인시 처인구 역북동 746번지 113호",
    type: "snack",
    subName: "간이음식점",
    imagePath: "uploads/snack1.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "색동다리분식",
    address: "경기도 용인시 처인구 중부대로 1305 홍양빌딩 1층",
    type: "snack",
    subName: "간이음식점",
    imagePath: "uploads/snack2.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "포곡분식",
    address: "경기도 용인시 처인구 포곡읍 삼계리 666-10번지",
    type: "snack",
    subName: "간이음식점",
    imagePath: "uploads/snack3.jpeg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const reviews = [
  {
    userName: "gigi",
    rating: 4,
    comment:
      "은화삼cc 근처에 위치한 한식당. 음식점 이름처럼 넓은 뜰이 있고 야외테이블에서 식사할 수 있다. 여러가지 음식을 제공하는데, 한정식은 반찬 종류와 가짓수에 따라서 3가지로 주문할수 있다. 가격은 좀 비싼편이지만 돌솥에 직접 해온 쌀밥은 고소하고 맛있다.반찬이나 찌게도 전반적으로 맛있다.",
    date: new Date(),
    store_id: 23,
  },
  {
    userName: "코끼리사자",
    rating: 4,
    comment:
      "주차장 넓고 분위기 괜찮은 듯. 가격은 최근 가격 반영되어 마음의 준비해야할 듯",
    date: new Date(),
    store_id: 23,
  },
  {
    userName: "고동",
    rating: 5,
    comment:
      "한적한 전원주택같은 편안함과 몸이 건강해지는것같은 담백하고 깔끔한 음식이 넘 잘어울리는 집",
    date: new Date(),
    store_id: 23,
  },
];

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert("store", stores, {});
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("store", null, {});
  },
};
